version: '3.8'

services:
  newrelic-sse-agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: newrelic-sse-agent
    ports:
      - "8000:8000"
    environment:
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
      - NEW_RELIC_ACCOUNT_ID=${NEW_RELIC_ACCOUNT_ID}
      - PORT=8000
      - ENVIRONMENT=production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - newrelic-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: newrelic-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - newrelic-sse-agent
    networks:
      - newrelic-network
    restart: unless-stopped
    profiles:
      - production

  # Optional: Redis for caching (if needed for scaling)
  redis:
    image: redis:7-alpine
    container_name: newrelic-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - newrelic-network
    restart: unless-stopped
    profiles:
      - caching

volumes:
  redis_data:

networks:
  newrelic-network:
    driver: bridge